#!/bin/bash

MAPPING_PATH=./mapping/generic_mapper_csv.groovy
HOST=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'|grep -v "172.17.0.1")
echo $HOST

#point to DGL home
DGL_DIR=$(ls /tmp/dse-graph-loader-*/dse-graph-loader-*-uberjar.jar)
DATA_DIR="data/"
GRAPH_NAME="genericgraph"
FILENAME_PATTERN=".csv"
DATA_FULL_DIR="$PWD"/"$DATA_DIR"

if [ -d /mnt/ephemeral/ebdata ]; then
    DATA_FULL_DIR="/mnt/ephemeral/ebdata/"
    DATA_DIR="/mnt/ephemeral/ebdata/"
fi

if [ -n "$1" ]; then
  HOST=$1
fi

set -e
set -x
TMPDIR="/mnt/tmp"
if [ ! -d "$TMPDIR" ]; then
  sudo mkdir "$TMPDIR"
  sudo chown ${USER} ${TMPDIR}
fi

rm -f loader.log loader.gclog loadedfiles.txt
echo "Started: " + $(date) >> loadedfiles.txt

#on linux you can say ls -1fd to get the full path. I added awk here to keep osx compatibility
FILES=($(ls -1f $(echo "$DATA_DIR") | grep "$FILENAME_PATTERN"|awk -v wd="$DATA_FULL_DIR" '{print wd $0}'|sort))
FILECOUNT=${#FILES[@]}
BUCKETSIZE=40

BUCKETCOUNT=$((($FILECOUNT / $BUCKETSIZE) +1))
LASTBUCKET=$(($FILECOUNT % $BUCKETSIZE))

echo "$FILES"
if [ -z "$FILES" ]; then
    echo "no files found"
    exit 1;
fi

echo $FILES

trap "exit" INT
#for f in /mnt/new-data/new-data-10M.json.*a.gz; do
for bucket in `seq "$BUCKETCOUNT"` ; do
  INDEX=$(((0+$bucket-1)*$BUCKETSIZE))
  LENGTH=$BUCKETSIZE

  #echo $INDEX

  #echo "{FILES[@]:$INDEX:$LENGTH}"
  FILELISTCOUNT=$(echo "${FILES[@]:$INDEX:$LENGTH}"|wc -w )
  FILELIST=$(echo "${FILES[@]:$INDEX:$LENGTH}")
  echo "Processing $FILELISTCOUNT Files: $FILELIST"

#grc is nice for aesthetics, if you don't want to install it just comment out this line.
  grc \
    java \
      -Xloggc:loader.gclog \
      -XX:+PrintGCDateStamps \
      -XX:+PrintGCDetails \
      -XX:+PrintTenuringDistribution \
      -XX:+PrintGCApplicationStoppedTime \
      -XX:+PrintGCCause \
      -XX:+HeapDumpOnOutOfMemoryError \
      -XX:HeapDumpPath=. \
      -Djava.io.tmpdir=/mnt/tmp \
      -jar "$DGL_DIR" \
      -graph "$GRAPH_NAME" \
      -address "$HOST" \
      "$MAPPING_PATH" \
      -inputfilename "$FILELIST" \
      -load_vertex_threads 32 \
      -load_edge_threads 32 \
            -read_threads 8 \
      -abort_on_num_failures $((1 * 1000 * 1000)) \
      -driver_retry_attempts 100 \
      -preparation false \
      -create_schema false \
      -load_new true \
      -vertex_complete false \
      && echo "$(date) Loaded " "$FILELIST" >> ./loadedfiles.txt

done
