#!/usr/bin/perl
#2016-05-31 16:20:42 INFO  Reporter:57 - ADD Request for 0 vertices 0 edges 175500 properties 0 anonymous
#2016-05-29 07:06:42 INFO  Reporter:57 - ADD Request for 5300 vertices 0 edges 0 properties 0 anonymous
#2017-01-16 19:12:58 INFO  Reporter:92 - ADD Request for 29600 vertices 0 edges 0 properties 0 anonymous
#2017-01-16 19:12:58 INFO  Reporter:97 - Current total additions: 7597500 vertices 0 edges 0 properties 0 anonymous
use strict;
use warnings;
open(my $vertex_throughput, '>', 'vertex-throughput.csv');
open(my $edge_throughput, '>', 'edge-throughput.csv');
open(my $property_throughput, '>', 'property-throughput.csv');
open(my $anonymous_throughput, '>', 'anonymous-throughput.csv');
my $current_file_handler;
my $avg_vertex_throughput = 0;
my $avg_edge_throughput = 0;
my $avg_property_throughput = 0;
my $avg_anonymous_throughput = 0;
my $number_of_vertex_data_points = 0;
my $number_of_edge_data_points = 0;
my $number_of_property_data_points = 0;
my $number_of_anonymous_data_points = 0;
while(<>) {
    if(/^(....-..-.. ..:..:..) .* - ADD Request for (.*) vertices (.*) edges (.*) properties (.*) anonymous$/) {
        if($2 != 0) {
            print $vertex_throughput "$1;$2\n";
            $avg_vertex_throughput = ($avg_vertex_throughput * $number_of_vertex_data_points + $2) / ($number_of_vertex_data_points + 1);
            $number_of_vertex_data_points++;
        }
        if($3 != 0) {
            print $edge_throughput "$1;$3\n";
            $avg_edge_throughput = ($avg_edge_throughput * $number_of_edge_data_points + $3) / ($number_of_edge_data_points + 1);
            $number_of_edge_data_points++;
        }
        if($4 != 0) {
            print $property_throughput "$1;$4\n";
            $avg_property_throughput = ($avg_property_throughput * $number_of_property_data_points + $4) / ($number_of_property_data_points + 1);
            $number_of_property_data_points++;
        }
        if($5 != 0) {
            print $anonymous_throughput "$1;$5\n";
            $avg_anonymous_throughput = ($avg_anonymous_throughput * $number_of_anonymous_data_points + $5) / ($number_of_anonymous_data_points + 1);
            $number_of_anonymous_data_points++;
        }
    }
}
close $vertex_throughput;
close $edge_throughput;
close $property_throughput;
close $anonymous_throughput;
sub format_number {
    my $text = reverse int($_[0]);
    $text =~ s/(\d\d\d)(?=\d)(?!\d*\.)/$1,/g;
    return scalar reverse $text;
}
printf "Element       | Number of measurements | Average throughput (ops/s) | Total number of elements\n";
printf "------------- | ---------------------- | -------------------------- | ------------------------\n";
printf "Vertices      | %22s | %26s | %24s\n", $number_of_vertex_data_points, format_number($avg_vertex_throughput), format_number($avg_vertex_throughput * $number_of_vertex_data_points);
printf "Edges         | %22s | %26s | %24s\n", $number_of_edge_data_points, format_number($avg_edge_throughput), format_number($avg_edge_throughput * $number_of_edge_data_points);
printf "Properties    | %22s | %26s | %24s\n", $number_of_property_data_points, format_number($avg_property_throughput), format_number($avg_property_throughput * $number_of_property_data_points);
printf "Anonymous     | %22s | %26s | %24s\n", $number_of_anonymous_data_points, format_number($avg_anonymous_throughput), format_number($avg_anonymous_throughput * $number_of_anonymous_data_points);

